#!/bin/bash

export CONF_DIR=/var/vcap/jobs/cockroachdb/config
export LOG_DIR=/var/vcap/sys/log/cockroachdb

mkdir -p           $LOG_DIR
chown -R vcap:vcap $LOG_DIR

/var/vcap/packages/cockroachdb/cockroach quit \
  --certs-dir=$CONF_DIR/certs \
  --host=0.0.0.0 \
  --port=<%= p("port") %> \
  --log-dir=$LOG_DIR \
  --logtostderr=INFO \
  --no-color \
  >>$LOG_DIR/stdout.log \
  2>>$LOG_DIR/stderr.log

echo 0
