#!/bin/bash

export CONF_DIR=/var/vcap/jobs/cockroachdb/config
export LOG_DIR=/var/vcap/sys/log/cockroachdb

mkdir -p           $LOG_DIR
chown -R vcap:vcap $LOG_DIR

/var/vcap/packages/cockroachdb/cockroach quit \
  --ca-cert=$CONF_DIR/cert_ca \
  --cert=$CONF_DIR/cert \
  --key=$CONF_DIR/cert_private_key \
  --host=0.0.0.0 \
  --port=<%= p("port") %> \
  --log-dir=$LOG_DIR \
  --alsologtostderr \
  --no-color \
  >>$LOG_DIR/stdout.log \
  2>>$LOG_DIR/stderr.log

echo 0
