#!/bin/bash

set -e

certs_path=/var/vcap/data/create-user/certs
rm -rf $certs_path
mkdir -p $certs_path

cp /var/vcap/jobs/create-user/config/certs/* $certs_path/
mv $certs_path/client.crt $certs_path/client.<%= p("user") %>.crt
mv $certs_path/client.key $certs_path/client.<%= p("user") %>.key

chmod 600 $certs_path/*
chown vcap:vcap $certs_path/*

# todo what if first instance is not available?
export COCKROACH_HOST=<%= link("conn").instances.first.address %>
export COCKROACH_PORT=<%= link("conn").p("port") %>

/var/vcap/packages/cockroachdb/cockroach \
  user set --user root --certs-dir $certs_path <%= p("user") %> >/dev/null

/var/vcap/packages/cockroachdb/cockroach \
  sql --user root --certs-dir $certs_path \
  -e "GRANT <%= p("privileges").join(",") %> ON DATABASE <%= link("database").p("name") %> TO <%= p("user") %>;"  >/dev/null

echo "{
  \"host\": \"${COCKROACH_HOST}\",
  \"port\": \"${COCKROACH_PORT}\",

  \"username\": \"<%= p("user") %>\",
  \"database\": \"<%= link("database").p("name") %>\",

  \"ca.crt\":     \"$(cat /var/vcap/jobs/create-user/config/certs/ca.crt    |perl -p -e 's/\n/\\n/')\",
  \"client.crt\": \"$(cat /var/vcap/jobs/create-user/config/certs/client.crt|perl -p -e 's/\n/\\n/')\",
  \"client.key\": \"$(cat /var/vcap/jobs/create-user/config/certs/client.key|perl -p -e 's/\n/\\n/')\"
}"
