#!/bin/bash

# Generate certs directory
certs_path=/var/vcap/data/cockroachdb_user/certs
rm -rf $certs_path
mkdir -p $certs_path

cp /var/vcap/jobs/cockroachdb_user/config/certs/* $certs_path/
mv $certs_path/client.crt $certs_path/client.<%= p("user") %>.crt
mv $certs_path/client.key $certs_path/client.<%= p("user") %>.key

chmod 600 $certs_path/*
chown vcap:vcap $certs_path/*

# todo what if first instance is not available?
export COCKROACH_HOST=<%= link("conn").instances.first.address %>
export COCKROACH_PORT=<%= link("conn").p("port") %>

exec /var/vcap/packages/cockroachdb/cockroach --certs-dir=$certs_path "$@"
