#!/bin/bash

set -e

certs_path=/var/vcap/data/delete-user/certs
rm -rf $certs_path
mkdir -p $certs_path

cp /var/vcap/jobs/delete-user/config/certs/* $certs_path/

chmod 600 $certs_path/*
chown vcap:vcap $certs_path/*

# todo what if first instance is not available?
export COCKROACH_HOST=<%= link("conn").instances.first.address %>
export COCKROACH_PORT=<%= link("conn").p("port") %>

/var/vcap/packages/cockroachdb/cockroach \
  sql --user root --certs-dir $certs_path \
  -e "REVOKE ALL ON DATABASE <%= link("database").p("name") %> FROM <%= p("user") %>;"

/var/vcap/packages/cockroachdb/cockroach \
  user rm --user root --certs-dir $certs_path <%= p("user") %>
